//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluationSystemDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public int CategoryId { get; set; }
        public string TagDescription { get; set; }
        public int QuestionId { get; set; }
    
        public virtual question question { get; set; }
    }
}
