//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluationSystemDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class evaluationsystemEntities1 : DbContext
    {
        public evaluationsystemEntities1()
            : base("name=evaluationsystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> category { get; set; }
        public DbSet<commentary> commentary { get; set; }
        public DbSet<evaluation> evaluation { get; set; }
        public DbSet<question> question { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<usersevaluationquestion> usersevaluationquestion { get; set; }
    }
}
