//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluationSystemDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public question()
        {
            this.category = new HashSet<category>();
            this.commentary = new HashSet<commentary>();
            this.usersevaluationquestion = new HashSet<usersevaluationquestion>();
            this.evaluation = new HashSet<evaluation>();
        }
    
        public int QuestionId { get; set; }
        public string Enunciation { get; set; }
        public string AnswerA { get; set; }
        public string AnswerB { get; set; }
        public string AnswerC { get; set; }
        public string AnswerD { get; set; }
        public string AnswerE { get; set; }
        public string CorrectAnswer { get; set; }
    
        public virtual ICollection<category> category { get; set; }
        public virtual ICollection<commentary> commentary { get; set; }
        public virtual ICollection<usersevaluationquestion> usersevaluationquestion { get; set; }
        public virtual ICollection<evaluation> evaluation { get; set; }
    }
}
