//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluationSystemModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EvaluationSystemEntities : DbContext
    {
        public EvaluationSystemEntities()
            : base("name=EvaluationSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<commentary> commentary { get; set; }
        public virtual DbSet<evaluation> evaluation { get; set; }
        public virtual DbSet<question> question { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<usersevaluationquestion> usersevaluationquestion { get; set; }
    }
}
